apiVersion: v2
version: "1.0"
name: umbrella-demo-app
dependencies:
- name: nginx-demo
  version: 0.1.0
  repository: file:///Users/san40/work/airSlate/knowledge-sharing/5_Nginx_demo_chart/nginx-demo
  alias: nginx-demo-1
- name: nginx-demo
  version: 0.1.0
  repository: file:///Users/san40/work/airSlate/knowledge-sharing/5_Nginx_demo_chart/nginx-demo
  alias: nginx-demo-2