apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knowledge-sharing-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  project: default
  source:
    repoURL: 'https://github.com/pdffiller/common-microservices-infra'
    path: apps/knowledge-sharing-app/dev
    targetRevision: knowledge-sharing-app
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.app_name
          value: knowledge-sharing-app
        - name: global.namespace
          value: apps
        - name: global.environment
          value: cinfra-dev
        - name: global.metric_prefix
          value: dev_apps_scaling
        - name: global.git.repoURL
          value: 'https://github.com/pdffiller/common-microservices-infra'
        - name: global.git.revision
          value: knowledge-sharing-app
        - name: global.git.path
          value: apps/knowledge-sharing-app/dev
      values: |
        global:
          logs:
          serviceMesh:
            enabled: true
            mesh: true
            gateways:
            - infra-istio/general-http-trust
            hosts:
            - knowledge-sharing-app.infrateam-dev.xyz
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry: {}

