apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: knowledge-sharing
  labels:
    app: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: nginx:1.25.3
        ports:
        - containerPort: 80
